/**
 * Seed Script — Properties
 * Run: node src/seed/seedProperties.js
 *
 * Inserts curated Pune luxury listings into MongoDB.
 * Safe to re-run: clears old data and re-inserts.
 */

import mongoose from 'mongoose';
import dotenv from 'dotenv';
import { fileURLToPath } from 'url';
import { dirname, resolve } from 'path';

const __dirname = dirname(fileURLToPath(import.meta.url));
dotenv.config({ path: resolve(__dirname, '../../.env') });

import Property from '../models/Property.js';
import User from '../models/User.js';

const properties = [
  {
    title: 'KP Grand Penthouse',
    type: 'Penthouse',
    category: 'Luxury Apartments',
    price: 120000000,
    priceLabel: '₹12 Cr',
    location: 'KP, Pune',
    city: 'Pune',
    bedrooms: 5,
    bathrooms: 5,
    area: 4800,
    parking: 3,
    image: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&q=80',
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&q=80',
      'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800&q=80',
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&q=80',
    ],
    badge: 'Featured',
    badgeColor: 'gold',
    status: 'Ready to Move',
    featured: true,
    amenities: ['Rooftop Deck', 'Smart Home Control', 'Italian Kitchen', 'Private Lounge', 'Valet Parking', 'Concierge Service', 'Jacuzzi', 'Home Theatre'],
    description: "Located in Pune's most prestigious address — Koregaon Park (KP). This penthouse features a private rooftop lounge, customized designer wardrobes, premium wellness spaces, and complete home automation by Crestron.",
    agent: { id: 1, name: 'Arjun Kapoor', phone: '+91 98765 43210' },
    yearBuilt: 2024,
    furnishing: 'Fully Furnished',
    facing: 'East Facing',
    developer: 'Panchshil Realty',
    rera: 'P52100046789',
    coordinates: { lat: 18.5362, lng: 73.8930 },
  },
  {
    title: 'Balewadi Premium Villa',
    type: 'Villa',
    category: 'Luxury Villas',
    price: 185000000,
    priceLabel: '₹18.5 Cr',
    location: 'Balewadi, Pune',
    city: 'Pune',
    bedrooms: 5,
    bathrooms: 6,
    area: 7800,
    parking: 4,
    image: 'https://images.unsplash.com/photo-1613977257363-707ba9348227?w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1613977257363-707ba9348227?w=800&q=80',
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&q=80',
      'https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=800&q=80',
    ],
    badge: 'New Launch',
    badgeColor: 'green',
    status: 'Under Construction',
    featured: true,
    amenities: ['Private Lawn', 'Infinity Pool', 'Home Automation', 'Basement Theatre', 'Elevator', 'Gym', 'Staff Quarters', 'EV Charging Spot'],
    description: "A spectacular contemporary villa in Balewadi — one of Pune's fastest-growing premium corridors. Designed by leading architects, this residence combines expansive double-height living areas, a private pool, and curated landscape gardens for ultimate luxury.",
    agent: { id: 2, name: 'Priya Sharma', phone: '+91 98765 43211' },
    yearBuilt: 2025,
    furnishing: 'Shell Condition',
    facing: 'North-East Facing',
    developer: 'Kolte-Patil Developers',
    rera: 'P52100051234',
    coordinates: { lat: 18.5651, lng: 73.7778 },
  },
  {
    title: 'Prabhat Road Luxury Duplex',
    type: 'Apartment',
    category: 'Luxury Apartments',
    price: 58000000,
    priceLabel: '₹5.8 Cr',
    location: 'Prabhat Road, Pune',
    city: 'Pune',
    bedrooms: 3,
    bathrooms: 3,
    area: 2800,
    parking: 2,
    image: 'https://images.unsplash.com/photo-1600607687644-c7171b46b83a?w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1600607687644-c7171b46b83a?w=800&q=80',
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&q=80',
    ],
    badge: 'Trending',
    badgeColor: 'blue',
    status: 'Ready to Move',
    featured: true,
    amenities: ['Private Terrace Garden', 'Clubhouse Access', 'Equipped Gym', 'Yoga Studio', '24/7 Security', 'High-Speed Elevators', 'Rooftop Lounge'],
    description: "An elegant duplex residence on Prabhat Road — one of Pune's most sought-after tree-lined avenues in the heart of the city. Features floor-to-ceiling glass paneling, smart home controls, and a gorgeous landscaped private terrace.",
    agent: { id: 3, name: 'Rahul Mehta', phone: '+91 98765 43212' },
    yearBuilt: 2023,
    furnishing: 'Semi Furnished',
    facing: 'East Facing',
    developer: 'Rohan Builders',
    rera: 'P52100048765',
    coordinates: { lat: 18.5161, lng: 73.8373 },
  },
  {
    title: 'Swargate Grand Estate',
    type: 'Villa',
    category: 'Luxury Villas',
    price: 95000000,
    priceLabel: '₹9.5 Cr',
    location: 'Swargate, Pune',
    city: 'Pune',
    bedrooms: 6,
    bathrooms: 7,
    area: 6200,
    parking: 5,
    image: 'https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800&q=80',
      'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800&q=80',
    ],
    badge: 'Exclusive',
    badgeColor: 'gold',
    status: 'Ready to Move',
    featured: true,
    amenities: ['Private Infinity Pool', 'Meditation Pavilion', 'Home Cinema', 'Bespoke Wine Cellar', 'Professional Kitchen', 'EV Chargers'],
    description: "A masterpiece of luxury real estate in Swargate — a prestigious central Pune location. Spanning 6,200 sqft of exquisite living spaces with natural stone, pristine water bodies, and custom light installations.",
    agent: { id: 1, name: 'Arjun Kapoor', phone: '+91 98765 43210' },
    yearBuilt: 2024,
    furnishing: 'Fully Furnished',
    facing: 'North-East Facing',
    developer: 'Goel Ganga Developments',
    rera: 'P52100049012',
    coordinates: { lat: 18.4953, lng: 73.8616 },
  },
  {
    title: 'Elysian Heights KP',
    type: 'Penthouse',
    category: 'Luxury Apartments',
    price: 120000000,
    priceLabel: '₹12 Cr',
    location: 'KP, Pune',
    city: 'Pune',
    bedrooms: 5,
    bathrooms: 5,
    area: 4800,
    parking: 3,
    image: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800&q=80',
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&q=80',
    ],
    badge: 'Featured',
    badgeColor: 'gold',
    status: 'Ready to Move',
    featured: false,
    amenities: ['Rooftop Deck', 'Smart Home Control', 'Italian Kitchen', 'Private Lounge', 'Valet Parking', 'Concierge Service'],
    description: "Located in Pune's most prestigious location — KP (Koregaon Park). This penthouse features a private rooftop lounge, customized designer wardrobes, premium wellness spaces, and complete home automation by Crestron.",
    agent: { id: 4, name: 'Neha Gupta', phone: '+91 98765 43213' },
    yearBuilt: 2024,
    furnishing: 'Fully Furnished',
    facing: 'East Facing',
    developer: 'Panchshil Realty',
    rera: 'P52100046789',
    coordinates: { lat: 18.5362, lng: 73.8930 },
  },
  {
    title: 'Pashan Eco Villa',
    type: 'Villa',
    category: 'Luxury Villas',
    price: 78000000,
    priceLabel: '₹7.8 Cr',
    location: 'Pashan, Pune',
    city: 'Pune',
    bedrooms: 4,
    bathrooms: 5,
    area: 4200,
    parking: 3,
    image: 'https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?w=800&q=80',
      'https://images.unsplash.com/photo-1505873242700-f289a29e1724?w=800&q=80',
    ],
    badge: 'Green Living',
    badgeColor: 'blue',
    status: 'Ready to Move',
    featured: true,
    amenities: ['Organic Garden', 'Solar Panels', 'Rainwater Harvesting', 'Infinity Pool', 'Sunset Lounge', 'EV Charging Station', 'Full Power Backup'],
    description: "A bespoke eco-friendly sanctuary in Pashan — Pune's green lung. Featuring solar-powered infinity pool, lush organic gardens, and panoramic Sahyadri hillside views.",
    agent: { id: 2, name: 'Priya Sharma', phone: '+91 98765 43211' },
    yearBuilt: 2023,
    furnishing: 'Fully Furnished',
    facing: 'West Facing',
    developer: 'Kumar Properties',
    rera: 'P52100047321',
    coordinates: { lat: 18.5348, lng: 73.8008 },
  },
  {
    title: 'Karve Nagar Signature Estate',
    type: 'Villa',
    category: 'Luxury Villas',
    price: 145000000,
    priceLabel: '₹14.5 Cr',
    location: 'Karve Nagar, Pune',
    city: 'Pune',
    bedrooms: 6,
    bathrooms: 8,
    area: 8500,
    parking: 6,
    image: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=800&q=80',
    ],
    badge: 'Heritage',
    badgeColor: 'gold',
    status: 'Ready to Move',
    featured: false,
    amenities: ['Manicured Gardens', 'Olympic Size Pool', 'Separate Banquet Hall', 'Smart Security System', 'Staff Housing (4 Rooms)', 'Private Study'],
    description: "A rare and prized heritage-style estate in Karve Nagar — one of Pune's most sought-after residential neighbourhoods. Built over a sprawling plot with manicured gardens, high ceilings, and state-of-the-art modern comforts.",
    agent: { id: 3, name: 'Rahul Mehta', phone: '+91 98765 43212' },
    yearBuilt: 2021,
    furnishing: 'Fully Furnished',
    facing: 'North Facing',
    developer: 'Rohan Builders',
    rera: 'P52100045678',
    coordinates: { lat: 18.4996, lng: 73.8334 },
  },
  {
    title: 'Kothrud Sky Villa',
    type: 'Apartment',
    category: 'Luxury Apartments',
    price: 75000000,
    priceLabel: '₹7.5 Cr',
    location: 'Kothrud, Pune',
    city: 'Pune',
    bedrooms: 4,
    bathrooms: 4,
    area: 4200,
    parking: 3,
    image: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800&q=80',
    ],
    badge: 'Hot Deal',
    badgeColor: 'red',
    status: 'Ready to Move',
    featured: false,
    amenities: ['Sky Pool', 'Private Bar', 'Dedicated Concierge', 'Smart Lighting', 'EV Parking Bays', 'VRV Airconditioning'],
    description: "A stunning sky villa in Kothrud — Pune's most vibrant residential hub. This spacious double-height apartment offers wrap-around balconies, private sky plunge pool, and automated interiors tailored for high-flying professionals.",
    agent: { id: 4, name: 'Neha Gupta', phone: '+91 98765 43213' },
    yearBuilt: 2024,
    furnishing: 'Semi Furnished',
    facing: 'East Facing',
    developer: 'Majestique Landmarks',
    rera: 'P52100053456',
    coordinates: { lat: 18.5074, lng: 73.8077 },
  },
  {
    title: 'Baner Highrise Signature',
    type: 'Apartment',
    category: 'Luxury Apartments',
    price: 42000000,
    priceLabel: '₹4.2 Cr',
    location: 'Baner, Pune',
    city: 'Pune',
    bedrooms: 3,
    bathrooms: 3,
    area: 2100,
    parking: 2,
    image: 'https://images.unsplash.com/photo-1560185893-a55cbc8c57e3?w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1560185893-a55cbc8c57e3?w=800&q=80',
      'https://images.unsplash.com/photo-1574362848149-11496d93a7c7?w=800&q=80',
    ],
    badge: 'New Launch',
    badgeColor: 'green',
    status: 'Under Construction',
    featured: false,
    amenities: ['Rooftop Pool', 'Co-working Lounge', 'Electric Car Charging', 'Concierge', 'Gym', '24/7 Security'],
    description: "A refined high-rise in Pune's burgeoning Baner tech corridor. Designed for the modern executive with co-working zones, rooftop infinity pool, and panoramic Sahyadri views — a rare blend of workspace convenience and luxury living.",
    agent: { id: 4, name: 'Neha Gupta', phone: '+91 98765 43213' },
    yearBuilt: 2026,
    furnishing: 'Shell Condition',
    facing: 'North Facing',
    developer: 'Kumar Properties',
    rera: 'P52100050123',
    coordinates: { lat: 18.5590, lng: 73.7797 },
  },
  {
    title: 'Hinjewadi Phase I Tech Residency',
    type: 'Apartment',
    category: 'Luxury Apartments',
    price: 55000000,
    priceLabel: '₹5.5 Cr',
    location: 'Hinjewadi Phase I, II, Pune',
    city: 'Pune',
    bedrooms: 3,
    bathrooms: 3,
    area: 1850,
    parking: 2,
    image: 'https://images.unsplash.com/photo-1505691723518-36a5ac3be353?w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1505691723518-36a5ac3be353?w=800&q=80',
      'https://images.unsplash.com/photo-1518780664697-55e3ad937233?w=800&q=80',
    ],
    badge: 'Exclusive',
    badgeColor: 'gold',
    status: 'Under Construction',
    featured: true,
    amenities: ['Clubhouse', 'Swimming Pool', 'Organic Garden', "Chef's Kitchen", 'Power Backup', 'Kids Play Zone'],
    description: "Strategically located in Hinjewadi Phase I & II — Pune's largest IT park hub. This premium residency offers tech-forward smart living with co-working spaces and proximity to Infosys, Wipro, and TCS campuses.",
    agent: { id: 1, name: 'Arjun Kapoor', phone: '+91 98765 43210' },
    yearBuilt: 2026,
    furnishing: 'Shell Condition',
    facing: 'West Facing',
    developer: 'Naiknavare Developers',
    rera: 'P52100052890',
    coordinates: { lat: 18.5906, lng: 73.7260 },
  },
  {
    title: 'Viman Nagar Sky Residence',
    type: 'Apartment',
    category: 'Luxury Apartments',
    price: 68000000,
    priceLabel: '₹6.8 Cr',
    location: 'Viman Nagar, Pune',
    city: 'Pune',
    bedrooms: 4,
    bathrooms: 4,
    area: 3400,
    parking: 2,
    image: 'https://images.unsplash.com/photo-1556909212-d5b604d0c90d?w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1556909212-d5b604d0c90d?w=800&q=80',
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&q=80',
    ],
    badge: 'Trending',
    badgeColor: 'blue',
    status: 'Ready to Move',
    featured: false,
    amenities: ['Sky Deck', 'Wine Room', 'Professional Gym', 'Steam & Sauna', 'Visitor Lounge', 'Power Backup'],
    description: "Positioned atop one of Viman Nagar's most sought-after towers — close to Pune Airport and Kalyani Nagar. This 4BHK sky residence offers sweeping views of Pune's skyline with Italian marble, smart controls, and a private sky deck.",
    agent: { id: 4, name: 'Neha Gupta', phone: '+91 98765 43213' },
    yearBuilt: 2024,
    furnishing: 'Semi Furnished',
    facing: 'South-West Facing',
    developer: 'Kolte Patil Developers',
    rera: 'P52100047856',
    coordinates: { lat: 18.5548, lng: 73.9142 },
  },
  {
    title: 'NIBM Road Forest Estate',
    type: 'Villa',
    category: 'Luxury Villas',
    price: 82000000,
    priceLabel: '₹8.2 Cr',
    location: 'NIBM Road, Pune',
    city: 'Pune',
    bedrooms: 5,
    bathrooms: 5,
    area: 5100,
    parking: 3,
    image: 'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=800&q=80',
    images: ['https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=800&q=80'],
    badge: 'Featured',
    badgeColor: 'gold',
    status: 'Ready to Move',
    featured: true,
    amenities: ['Private Garden', 'Forest View', 'Eco Architecture', '24/7 Security'],
    description: "Surrounded by lush green protected forest views in NIBM Road corridor. Elegant eco-friendly layout featuring custom wood finishes and large outdoor entertainment deck.",
    agent: { id: 3, name: 'Rahul Mehta', phone: '+91 98765 43212' },
    yearBuilt: 2023,
    furnishing: 'Fully Furnished',
    facing: 'East Facing',
    developer: 'Gera Developments',
    rera: 'P52100041239',
    coordinates: { lat: 18.4735, lng: 73.8978 },
  },
  {
    title: 'Kharadi IT Heights Apartment',
    type: 'Apartment',
    category: 'Luxury Apartments',
    price: 38000000,
    priceLabel: '₹3.8 Cr',
    location: 'Kharadi, Pune',
    city: 'Pune',
    bedrooms: 3,
    bathrooms: 3,
    area: 2300,
    parking: 2,
    image: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800&q=80',
    images: ['https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800&q=80'],
    badge: 'Trending',
    badgeColor: 'blue',
    status: 'Ready to Move',
    featured: false,
    amenities: ['Gym', 'Rooftop Lounge', 'Home Automation', 'Power Backup'],
    description: "Strategically located in Pune's IT hub, Kharadi. Offers proximity to EON Free Zone and World Trade Center. Modern amenities with high automation capabilities.",
    agent: { id: 2, name: 'Priya Sharma', phone: '+91 98765 43211' },
    yearBuilt: 2024,
    furnishing: 'Fully Furnished',
    facing: 'East Facing',
    developer: 'Gera Developments',
    rera: 'P52100041240',
    coordinates: { lat: 18.5492, lng: 73.9482 },
  },
  {
    title: 'Punewadi Waterfront Residency',
    type: 'Apartment',
    category: 'Luxury Apartments',
    price: 29000000,
    priceLabel: '₹2.9 Cr',
    location: 'Punewadi, Pune',
    city: 'Pune',
    bedrooms: 3,
    bathrooms: 3,
    area: 1950,
    parking: 2,
    image: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&q=80',
    images: ['https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&q=80'],
    badge: 'New Launch',
    badgeColor: 'green',
    status: 'Under Construction',
    featured: true,
    amenities: ['Riverfront View', 'Yoga Deck', 'Jogging Track', 'Swimming Pool'],
    description: "Enjoy stunning sunrise views of the river in Punewadi's premium highrise development. Masterfully crafted with premium marble and modular kitchen settings.",
    agent: { id: 1, name: 'Arjun Kapoor', phone: '+91 98765 43210' },
    yearBuilt: 2026,
    furnishing: 'Shell Condition',
    facing: 'North Facing',
    developer: 'VTP Realty',
    rera: 'P52100041241',
    coordinates: { lat: 18.5701, lng: 73.9512 },
  },
  {
    title: 'MG Road Heritage Business Suite',
    type: 'Commercial',
    category: 'Commercial',
    price: 110000000,
    priceLabel: '₹11 Cr',
    location: 'MG Road, Pune',
    city: 'Pune',
    bedrooms: 0,
    bathrooms: 4,
    area: 4500,
    parking: 4,
    image: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&q=80',
    images: ['https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&q=80'],
    badge: 'Exclusive',
    badgeColor: 'gold',
    status: 'Ready to Move',
    featured: false,
    amenities: ['Centrally Airconditioned', 'High-Speed Elevator', 'Vastu Compliant', 'Boardroom Setup'],
    description: "Premium retail & office hybrid layout right in the commercial pulse of MG Road. Offers maximum visibility and high-end security parameters.",
    agent: { id: 4, name: 'Neha Gupta', phone: '+91 98765 43213' },
    yearBuilt: 2022,
    furnishing: 'Fully Furnished',
    facing: 'North Facing',
    developer: 'Kumar Properties',
    rera: 'P52100041242',
    coordinates: { lat: 18.5142, lng: 73.8785 },
  },
  {
    title: 'JM Road Commercial Landmark',
    type: 'Commercial',
    category: 'Commercial',
    price: 150000000,
    priceLabel: '₹15 Cr',
    location: 'JM Road, Pune',
    city: 'Pune',
    bedrooms: 0,
    bathrooms: 6,
    area: 6800,
    parking: 6,
    image: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800&q=80',
    images: ['https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800&q=80'],
    badge: 'Hot Deal',
    badgeColor: 'red',
    status: 'Ready to Move',
    featured: true,
    amenities: ['Double Height Lobby', 'Central AC', 'EV Charging bays', '24/7 Security Operations'],
    description: "Highly visible corporate headquarters style building on Jangli Maharaj Road. Features premium double glass glazing and modern energy conservation panels.",
    agent: { id: 3, name: 'Rahul Mehta', phone: '+91 98765 43212' },
    yearBuilt: 2024,
    furnishing: 'Fully Furnished',
    facing: 'West Facing',
    developer: 'Rohan Builders',
    rera: 'P52100041243',
    coordinates: { lat: 18.5208, lng: 73.8475 },
  },
  {
    title: 'F.C. Road Signature Penthouse',
    type: 'Penthouse',
    category: 'Luxury Apartments',
    price: 62000000,
    priceLabel: '₹6.2 Cr',
    location: 'F.C. Road, Pune',
    city: 'Pune',
    bedrooms: 4,
    bathrooms: 4,
    area: 3200,
    parking: 2,
    image: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&q=80',
    images: ['https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&q=80'],
    badge: 'Trending',
    badgeColor: 'blue',
    status: 'Ready to Move',
    featured: false,
    amenities: ['Rooftop Terrace', 'Clubhouse Access', 'Infinity Edge Lounge', 'Automated Curtains'],
    description: "Perched high above Fergusson College Road. Perfect blend of youthful central energy and ultimate private enclave status with scenic view of Fergusson Hill.",
    agent: { id: 1, name: 'Arjun Kapoor', phone: '+91 98765 43210' },
    yearBuilt: 2024,
    furnishing: 'Fully Furnished',
    facing: 'North Facing',
    developer: 'Pride Purple Group',
    rera: 'P52100041244',
    coordinates: { lat: 18.5245, lng: 73.8415 },
  },
  {
    title: 'Bawadhan Hilltop Sanctuary',
    type: 'Villa',
    category: 'Luxury Villas',
    price: 75000000,
    priceLabel: '₹7.5 Cr',
    location: 'Bawadhan, Pune',
    city: 'Pune',
    bedrooms: 4,
    bathrooms: 5,
    area: 4400,
    parking: 3,
    image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&q=80',
    images: ['https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&q=80'],
    badge: 'Featured',
    badgeColor: 'gold',
    status: 'Ready to Move',
    featured: true,
    amenities: ['Infinity Sky Pool', 'Home Theatre', 'Hillside view', 'Solar Powered Grid'],
    description: "Located on a private hilltop ridge in Bawadhan. Masterfully designed modern architecture featuring panoramic hillside layouts and a stunning private infinity pool.",
    agent: { id: 2, name: 'Priya Sharma', phone: '+91 98765 43211' },
    yearBuilt: 2023,
    furnishing: 'Fully Furnished',
    facing: 'West Facing',
    developer: 'Nyati Group',
    rera: 'P52100041245',
    coordinates: { lat: 18.5085, lng: 73.7745 },
  },
  {
    title: 'Ravet Riverview Penthouse',
    type: 'Penthouse',
    category: 'Luxury Apartments',
    price: 48000000,
    priceLabel: '₹4.8 Cr',
    location: 'Ravet, Pune',
    city: 'Pune',
    bedrooms: 4,
    bathrooms: 4,
    area: 3100,
    parking: 2,
    image: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&q=80',
    images: ['https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&q=80'],
    badge: 'New Launch',
    badgeColor: 'green',
    status: 'Under Construction',
    featured: false,
    amenities: ['Sky Garden', 'Yoga Deck', 'EV Car Station', 'Home Gym'],
    description: "A fast-growing residential hotspot in PCMC corridor. Panoramic river views from the top-most floor. Smart specifications tailored for long-term HNI buyers.",
    agent: { id: 4, name: 'Neha Gupta', phone: '+91 98765 43213' },
    yearBuilt: 2026,
    furnishing: 'Shell Condition',
    facing: 'North Facing',
    developer: 'DGP Group',
    rera: 'P52100041246',
    coordinates: { lat: 18.6432, lng: 73.7485 },
  },
  {
    title: 'Ganga Dham Chownk Residence',
    type: 'Apartment',
    category: 'Luxury Apartments',
    price: 36000000,
    priceLabel: '₹3.6 Cr',
    location: 'Ganga Dham Chownk, Pune',
    city: 'Pune',
    bedrooms: 3,
    bathrooms: 3,
    area: 2100,
    parking: 2,
    image: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&q=80',
    images: ['https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&q=80'],
    badge: 'Hot Deal',
    badgeColor: 'red',
    status: 'Ready to Move',
    featured: true,
    amenities: ['Vastu Compliant', 'Banquet Hall', 'Indoor Games Arena', 'CCTV Security Grid'],
    description: "Elegant, centrally connected luxury apartment in Ganga Dham. Completely Vastu compliant facing east, featuring premium Italian modular kitchen units.",
    agent: { id: 1, name: 'Arjun Kapoor', phone: '+91 98765 43210' },
    yearBuilt: 2024,
    furnishing: 'Fully Furnished',
    facing: 'East Facing',
    developer: 'Goel Ganga Developments',
    rera: 'P52100041247',
    coordinates: { lat: 18.4789, lng: 73.8655 },
  },
  {
    title: 'Katraj Lakeview Villa',
    type: 'Villa',
    category: 'Luxury Villas',
    price: 52000000,
    priceLabel: '₹5.2 Cr',
    location: 'Katraj, Pune',
    city: 'Pune',
    bedrooms: 4,
    bathrooms: 4,
    area: 3900,
    parking: 3,
    image: 'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800&q=80',
    images: ['https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800&q=80'],
    badge: 'Exclusive',
    badgeColor: 'gold',
    status: 'Ready to Move',
    featured: false,
    amenities: ['Lake View Deck', 'Lush Landscaping', 'Solar Heaters', 'Staff Quarters'],
    description: "Private contemporary villa facing the serene waters of Katraj Lake. Fully customized with marble finishes, large walk-in wardrobes, and solar power setup.",
    agent: { id: 3, name: 'Rahul Mehta', phone: '+91 98765 43212' },
    yearBuilt: 2023,
    furnishing: 'Semi Furnished',
    facing: 'North Facing',
    developer: 'Amit Enterprises',
    rera: 'P52100041248',
    coordinates: { lat: 18.4525, lng: 73.8545 },
  },
];

async function seed() {
  try {
    await mongoose.connect(process.env.MONGO_URI);
    console.log('✅ MongoDB connected');

    // Fetch seeded agents
    const agents = await User.find({ role: 'agent' });
    console.log(`👤 Found ${agents.length} agents in the database`);

    // Dynamically assign properties based on location match
    for (const p of properties) {
      const locName = p.location.split(',')[0].trim().toLowerCase();
      
      const matchingAgent = agents.find(a => {
        if (!a.expertise) return false;
        const areas = a.expertise.split(',').map(s => s.trim().toLowerCase());
        return areas.some(area => area === locName || locName.includes(area) || area.includes(locName));
      });

      if (matchingAgent) {
        p.agent = {
          id: matchingAgent._id,
          name: matchingAgent.name,
          phone: matchingAgent.phone
        };
      } else {
        // Fallback: assign to a random agent
        const randomAgent = agents[Math.floor(Math.random() * agents.length)];
        if (randomAgent) {
          p.agent = {
            id: randomAgent._id,
            name: randomAgent.name,
            phone: randomAgent.phone
          };
        }
      }
    }

    // Clean up existing properties
    await Property.deleteMany({});
    console.log('🧹 Cleared existing properties database');

    const inserted = await Property.insertMany(properties);
    console.log(`🏠 Seeded ${inserted.length} Pune properties successfully with matched agent assignments!`);
  } catch (err) {
    console.error('❌ Seed failed:', err.message);
  } finally {
    await mongoose.disconnect();
    console.log('🔌 MongoDB disconnected');
  }
}

seed();
