/**
 * Seed Script — Properties
 * Run: node src/seed/seedProperties.js
 *
 * Inserts structured Pune listings aligned with current site filters (Buy, Rent, PG, Flatmates).
 * Safe to re-run: clears old data and re-inserts.
 */

import mongoose from 'mongoose';
import dotenv from 'dotenv';
import { fileURLToPath } from 'url';
import { dirname, resolve } from 'path';

const __dirname = dirname(fileURLToPath(import.meta.url));
dotenv.config({ path: resolve(__dirname, '../../.env') });

import Property from '../models/Property.js';
import User from '../models/User.js';

const properties = [
  // ── BUY PROPERTIES (Residential, Villa, Plot, Commercial) ────────────────────
  {
    title: 'KP Grand Penthouse',
    type: 'Penthouse',
    category: 'Luxury Apartments',
    price: 120000000,
    priceLabel: '₹12 Cr',
    location: 'Koregaon Park, Pune',
    city: 'Pune',
    bedrooms: 5,
    bathrooms: 5,
    area: 4800,
    parking: 3,
    image: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&q=80',
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&q=80',
    ],
    badge: 'Featured',
    badgeColor: 'gold',
    status: 'Ready to Move',
    featured: true,
    amenities: ['Rooftop Deck', 'Smart Home Control', 'Italian Kitchen', 'Private Lounge', 'Valet Parking', 'Concierge Service'],
    description: "Located in Pune's most prestigious address — Koregaon Park. This penthouse features a private rooftop lounge, customized designer wardrobes, and home automation.",
    yearBuilt: 2024,
    furnishing: 'Fully Furnished',
    facing: 'East Facing',
    developer: 'Panchshil Realty',
    rera: 'P52100046789',
    coordinates: { lat: 18.5362, lng: 73.8930 },
    listingType: 'Resale',
    propertyType: 'Residential',
    bhkType: '5 BHK',
    locality: 'Koregaon Park',
    propertyAge: 'Ready to Move',
  },
  {
    title: 'Balewadi Premium Villa',
    type: 'Villa',
    category: 'Luxury Villas',
    price: 85000000,
    priceLabel: '₹8.5 Cr',
    location: 'Balewadi, Pune',
    city: 'Pune',
    bedrooms: 5,
    bathrooms: 6,
    area: 5800,
    parking: 4,
    image: 'https://images.unsplash.com/photo-1613977257363-707ba9348227?w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1613977257363-707ba9348227?w=800&q=80',
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&q=80',
    ],
    badge: 'New Launch',
    badgeColor: 'green',
    status: 'Under Construction',
    featured: true,
    amenities: ['Private Lawn', 'Infinity Pool', 'Home Automation', 'Elevator', 'Gym', 'Staff Quarters'],
    description: "A spectacular contemporary villa in Balewadi. Combines expansive double-height living areas, private pool, and curated landscape gardens.",
    yearBuilt: 2025,
    furnishing: 'Shell Condition',
    facing: 'North-East Facing',
    developer: 'Kolte-Patil Developers',
    rera: 'P52100051234',
    coordinates: { lat: 18.5651, lng: 73.7778 },
    listingType: 'Resale',
    propertyType: 'Villa',
    bhkType: '5 BHK',
    locality: 'Balewadi',
    propertyAge: 'Under Construction',
  },
  {
    title: 'Kalyani Nagar Estate Plot',
    type: 'Plot',
    category: 'Luxury Plots',
    price: 150000000,
    priceLabel: '₹15 Cr',
    location: 'Kalyani Nagar, Pune',
    city: 'Pune',
    bedrooms: 0,
    bathrooms: 0,
    area: 12000,
    parking: 0,
    image: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800&q=80',
    images: ['https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800&q=80'],
    badge: 'Exclusive',
    badgeColor: 'gold',
    status: 'Ready to Move',
    featured: true,
    amenities: ['Boundary Wall', 'Gated Community', '24x7 Water', 'Electricity Connection'],
    description: "A prime residential plot measuring 12,000 sq ft located inside Kalyani Nagar's premium gated community. Highly suitable for building custom ultra-luxury bungalows.",
    yearBuilt: 2024,
    furnishing: 'Unfurnished',
    facing: 'East Facing',
    developer: 'Vascon Engineers',
    rera: 'P52100041235',
    coordinates: { lat: 18.5463, lng: 73.9032 },
    listingType: 'Resale',
    propertyType: 'Land/Plot',
    bhkType: 'Plot',
    locality: 'Kalyani Nagar',
    plotArea: '5000+',
  },
  {
    title: 'Bund Garden Executive Office',
    type: 'Commercial',
    category: 'Luxury Commercial',
    price: 45000000,
    priceLabel: '₹4.5 Cr',
    location: 'Bund Garden, Pune',
    city: 'Pune',
    bedrooms: 0,
    bathrooms: 2,
    area: 3200,
    parking: 4,
    image: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&q=80',
    images: ['https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&q=80'],
    badge: 'Hot Deal',
    badgeColor: 'red',
    status: 'Ready to Move',
    featured: false,
    amenities: ['Central A/C', '100% Power Backup', 'Reception Desk', 'Boardroom', 'CCTV Security Grid'],
    description: "A Grade-A office space in Bund Garden's premium corporate tower. Fully fitted layout with cabins, workstations, cafeteria, and panoramic city views.",
    yearBuilt: 2023,
    furnishing: 'Fully Furnished',
    facing: 'West Facing',
    developer: 'Kumar Properties',
    rera: 'P52100041236',
    coordinates: { lat: 18.5358, lng: 73.8789 },
    listingType: 'Resale',
    propertyType: 'Commercial',
    bhkType: 'Commercial',
    locality: 'Bund Garden',
    buildingType: 'Commercial Building',
  },

  // ── RENT PROPERTIES (Residential, Villa, Commercial) ──────────────────────────
  {
    title: 'Kharadi Riverside Apartment',
    type: 'Apartment',
    category: 'Premium Apartments',
    price: 65000,
    priceLabel: '₹65,000/mo',
    location: 'Kharadi, Pune',
    city: 'Pune',
    bedrooms: 3,
    bathrooms: 3,
    area: 1800,
    parking: 2,
    image: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&q=80',
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&q=80',
    ],
    badge: 'Trending',
    badgeColor: 'blue',
    status: 'Ready to Move',
    featured: true,
    amenities: ['Clubhouse Gym', 'Swimming Pool', 'Security Guard', 'Balcony Garden', 'Gas Pipeline'],
    description: "Beautiful 3 BHK river-view apartment in Kharadi, near IT park. Fully-fitted modular kitchen, wardrobes, LED lighting, and premium fixtures.",
    yearBuilt: 2022,
    furnishing: 'Fully Furnished',
    facing: 'East Facing',
    developer: 'Gera Developments',
    rera: 'P52100042109',
    coordinates: { lat: 18.5510, lng: 73.9525 },
    listingType: 'Rent',
    propertyType: 'Residential',
    bhkType: '3 BHK',
    locality: 'Kharadi',
    preferredTenant: 'Family',
    parkingType: 'Both',
  },
  {
    title: 'Viman Nagar Luxury Flat',
    type: 'Apartment',
    category: 'Premium Apartments',
    price: 45000,
    priceLabel: '₹45,000/mo',
    location: 'Viman Nagar, Pune',
    city: 'Pune',
    bedrooms: 2,
    bathrooms: 2,
    area: 1250,
    parking: 1,
    image: 'https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800&q=80',
      'https://images.unsplash.com/photo-1484154218962-a197022b5858?w=800&q=80',
      'https://images.unsplash.com/photo-1505691938895-1758d7feb511?w=800&q=80'
    ],
    badge: 'Popular',
    badgeColor: 'gold',
    status: 'Ready to Move',
    featured: false,
    amenities: ['100% Power Backup', 'Water Purifier', 'Elevator Access', 'Central Security'],
    description: "Located near Symbiosis College, Viman Nagar. This 2 BHK apartment comes with beds, sofa, dining table, modular kitchen, and private balconies.",
    yearBuilt: 2021,
    furnishing: 'Fully Furnished',
    facing: 'North Facing',
    developer: 'Lunkad Realty',
    rera: 'P52100042110',
    coordinates: { lat: 18.5679, lng: 73.9143 },
    listingType: 'Rent',
    propertyType: 'Residential',
    bhkType: '2 BHK',
    locality: 'Viman Nagar',
    preferredTenant: 'Bachelors',
    parkingType: 'Two Wheeler',
  },
  {
    title: 'Hadapsar Commercial IT Suite',
    type: 'Commercial',
    category: 'Premium Commercial',
    price: 180000,
    priceLabel: '₹1.8 L/mo',
    location: 'Hadapsar, Pune',
    city: 'Pune',
    bedrooms: 0,
    bathrooms: 2,
    area: 2500,
    parking: 3,
    image: 'https://images.unsplash.com/photo-1497215728101-856f4ea42174?w=800&q=80',
    images: ['https://images.unsplash.com/photo-1497215728101-856f4ea42174?w=800&q=80'],
    badge: 'Corporate Option',
    badgeColor: 'blue',
    status: 'Ready to Move',
    featured: false,
    amenities: ['High-speed Elevators', 'Corporate Lounge', 'Central AC', 'Secured Access Control'],
    description: "Fitted office space located in Hadapsar commercial corridor. Ideal for IT/consulting firms seeking immediate operations setup.",
    yearBuilt: 2023,
    furnishing: 'Semi Furnished',
    facing: 'East Facing',
    developer: 'Amanora Group',
    rera: 'P52100042111',
    coordinates: { lat: 18.5144, lng: 73.9430 },
    listingType: 'Rent',
    propertyType: 'Commercial',
    bhkType: 'Commercial',
    locality: 'Hadapsar',
    buildingType: 'IT Park',
  },

  // ── PG / HOSTELS (Residential) ────────────────────────────────────────────────
  {
    title: 'Viman Nagar Boys PG',
    type: 'Apartment',
    category: 'Hostel/Co-Living',
    price: 16000,
    priceLabel: '₹16,000/mo',
    location: 'Viman Nagar, Pune',
    city: 'Pune',
    bedrooms: 1,
    bathrooms: 1,
    area: 350,
    parking: 1,
    image: 'https://images.unsplash.com/photo-1598928506311-c55ded91a20c?w=800&q=80',
    images: ['https://images.unsplash.com/photo-1598928506311-c55ded91a20c?w=800&q=80'],
    badge: 'Popular for Students',
    badgeColor: 'gold',
    status: 'Ready to Move',
    featured: true,
    amenities: ['Daily Housekeeping', 'High Speed WiFi', 'Washing Machine', 'Filtered Drinking Water', 'TV Lounge'],
    description: "Premium single-occupancy PG for boys in Viman Nagar. Includes breakfast & dinner in the monthly rent. Walking distance from Symbiosis campus.",
    yearBuilt: 2023,
    furnishing: 'Fully Furnished',
    facing: 'East Facing',
    developer: 'Kin PG Management',
    coordinates: { lat: 18.5682, lng: 73.9149 },
    listingType: 'PG/Hostel',
    propertyType: 'Residential',
    bhkType: '1 BHK',
    locality: 'Viman Nagar',
    pgGender: 'Male',
    roomType: 'Single',
    pgFood: 'Breakfast, Dinner',
    tenantType: 'Student',
  },
  {
    title: 'Baner Premium Co-living Hub',
    type: 'Apartment',
    category: 'Hostel/Co-Living',
    price: 12000,
    priceLabel: '₹12,000/mo',
    location: 'Baner, Pune',
    city: 'Pune',
    bedrooms: 2,
    bathrooms: 2,
    area: 750,
    parking: 2,
    image: 'https://images.unsplash.com/photo-1554995207-c18c203602cb?w=800&q=80',
    images: ['https://images.unsplash.com/photo-1554995207-c18c203602cb?w=800&q=80'],
    badge: 'Co-Living',
    badgeColor: 'green',
    status: 'Ready to Move',
    featured: false,
    amenities: ['All Meals Included', 'Weekly Linen Change', 'Gym access', 'High Speed WiFi', 'Air Conditioned'],
    description: "Luxury double-sharing PG hostel for working professionals in Baner. Includes high-speed Wi-Fi, air conditioning, and laundry services.",
    yearBuilt: 2024,
    furnishing: 'Fully Furnished',
    facing: 'North Facing',
    developer: 'Kin PG Management',
    coordinates: { lat: 18.5590, lng: 73.7799 },
    listingType: 'PG/Hostel',
    propertyType: 'Residential',
    bhkType: '2 BHK',
    locality: 'Baner',
    pgGender: 'Any',
    roomType: 'Double',
    pgFood: 'All Meals',
    tenantType: 'Working Professional',
  },
  {
    title: 'Koregaon Park Girls Luxury PG',
    type: 'Apartment',
    category: 'Hostel/Co-Living',
    price: 22000,
    priceLabel: '₹22,000/mo',
    location: 'Koregaon Park, Pune',
    city: 'Pune',
    bedrooms: 1,
    bathrooms: 1,
    area: 400,
    parking: 1,
    image: 'https://images.unsplash.com/photo-1505691938895-1758d7feb511?w=800&q=80',
    images: ['https://images.unsplash.com/photo-1505691938895-1758d7feb511?w=800&q=80'],
    badge: 'Premium Security',
    badgeColor: 'gold',
    status: 'Ready to Move',
    featured: true,
    amenities: ['Biometric Access Control', 'Daily Meals', 'Power Backup', 'Personal Wardrobe', 'Balcony Unit'],
    description: "Highly secure premium single-occupancy co-living suite for female professionals in Koregaon Park. Safe neighborhood, biometric access.",
    yearBuilt: 2023,
    furnishing: 'Fully Furnished',
    facing: 'West Facing',
    developer: 'Panchshil Realty',
    coordinates: { lat: 18.5365, lng: 73.8942 },
    listingType: 'PG/Hostel',
    propertyType: 'Residential',
    bhkType: '1 BHK',
    locality: 'Koregaon Park',
    pgGender: 'Female',
    roomType: 'Single',
    pgFood: 'Breakfast, Lunch, Dinner',
    tenantType: 'Working Professional',
  },

  // ── FLATMATES (Residential) ───────────────────────────────────────────────────
  {
    title: 'Kothrud Cozy Room for Female Flatmate',
    type: 'Apartment',
    category: 'Flatmate Matching',
    price: 11000,
    priceLabel: '₹11,000/mo',
    location: 'Kothrud, Pune',
    city: 'Pune',
    bedrooms: 3,
    bathrooms: 3,
    area: 1600,
    parking: 1,
    image: 'https://images.unsplash.com/photo-1505693395321-883724634266?w=800&q=80',
    images: ['https://images.unsplash.com/photo-1505693395321-883724634266?w=800&q=80'],
    badge: 'Immediate Join',
    badgeColor: 'red',
    status: 'Ready to Move',
    featured: false,
    amenities: ['Washing Machine', 'Smart TV', 'High-Speed Internet', 'Gas Stove & Kitchen Setup'],
    description: "Looking for a friendly female flatmate to occupy a fully-furnished private bedroom in our 3 BHK flat in Kothrud. Chill vibes, clean environment.",
    yearBuilt: 2022,
    furnishing: 'Fully Furnished',
    facing: 'North Facing',
    developer: 'Amit Enterprises',
    coordinates: { lat: 18.5074, lng: 73.8077 },
    listingType: 'Flatmates',
    propertyType: 'Residential',
    bhkType: '1 BHK',
    locality: 'Kothrud',
    roomType: 'Single',
    tenantType: 'Female',
  },
  {
    title: 'Aundh Shared Room for Male Flatmate',
    type: 'Apartment',
    category: 'Flatmate Matching',
    price: 7500,
    priceLabel: '₹7,500/mo',
    location: 'Aundh, Pune',
    city: 'Pune',
    bedrooms: 2,
    bathrooms: 2,
    area: 1100,
    parking: 1,
    image: 'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800&q=80',
    images: ['https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800&q=80'],
    badge: 'Budget Friendly',
    badgeColor: 'blue',
    status: 'Ready to Move',
    featured: false,
    amenities: ['High-speed Internet', 'Water Geyser', 'Refrigerator', 'Bike Parking Lot'],
    description: "Shared room occupancy available for a working male flatmate in a 2 BHK apartment at Aundh. House is semi-furnished with basic cooking appliances.",
    yearBuilt: 2021,
    furnishing: 'Semi Furnished',
    facing: 'East Facing',
    developer: 'Paranjape Schemes',
    coordinates: { lat: 18.5580, lng: 73.8075 },
    listingType: 'Flatmates',
    propertyType: 'Residential',
    bhkType: '2 BHK',
    locality: 'Aundh',
    roomType: 'Shared',
    tenantType: 'Male',
  },

  // ── MORE BUY PROPERTIES FOR DIVERSITY ──────────────────────────────────────────
  {
    title: 'Aundh Luxury Garden Villa',
    type: 'Villa',
    category: 'Luxury Villas',
    price: 68000000,
    priceLabel: '₹6.8 Cr',
    location: 'Aundh, Pune',
    city: 'Pune',
    bedrooms: 4,
    bathrooms: 4,
    area: 4200,
    parking: 3,
    image: 'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=800&q=80',
    images: ['https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=800&q=80'],
    badge: 'Exclusive',
    badgeColor: 'gold',
    status: 'Ready to Move',
    featured: false,
    amenities: ['Spacious Lawn', 'Private Pool', 'Modular Kitchen', 'Servant Quarters'],
    description: "Beautiful modern design luxury villa in Aundh. Double height ceiling structure, private garden spaces, and modular fixtures.",
    yearBuilt: 2023,
    furnishing: 'Semi Furnished',
    facing: 'East Facing',
    developer: 'Paranjape Schemes',
    rera: 'P52100041239',
    coordinates: { lat: 18.5585, lng: 73.8062 },
    listingType: 'Resale',
    propertyType: 'Villa',
    bhkType: '4 BHK',
    locality: 'Aundh',
    propertyAge: '3-5 years',
  },
  {
    title: 'Baner Luxury Duplex Studio',
    type: 'Apartment',
    category: 'Luxury Apartments',
    price: 18500000,
    priceLabel: '₹1.85 Cr',
    location: 'Baner, Pune',
    city: 'Pune',
    bedrooms: 2,
    bathrooms: 2,
    area: 1200,
    parking: 1,
    image: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&q=80',
    images: ['https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&q=80'],
    badge: 'Trending',
    badgeColor: 'blue',
    status: 'Ready to Move',
    featured: true,
    amenities: ['Swimming Pool', 'Modular Kitchen', 'Clubhouse Lounge', 'Fitness Gym'],
    description: "Highly customized contemporary duplex suite for young professionals in Baner. Includes modular kitchen fittings and designer washrooms.",
    yearBuilt: 2024,
    furnishing: 'Fully Furnished',
    facing: 'North Facing',
    developer: 'Pride Purple Properties',
    rera: 'P52100041240',
    coordinates: { lat: 18.5592, lng: 73.7801 },
    listingType: 'Resale',
    propertyType: 'Residential',
    bhkType: '2 BHK',
    locality: 'Baner',
    propertyAge: 'Less than 1 year',
  },
  {
    title: 'Hadapsar Premium Plot',
    type: 'Plot',
    category: 'Luxury Plots',
    price: 32000000,
    priceLabel: '₹3.2 Cr',
    location: 'Hadapsar, Pune',
    city: 'Pune',
    bedrooms: 0,
    bathrooms: 0,
    area: 3600,
    parking: 0,
    image: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=800&q=80',
    images: ['https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=800&q=80'],
    badge: 'Featured Plot',
    badgeColor: 'gold',
    status: 'Ready to Move',
    featured: false,
    amenities: ['Water Connection', 'Tar Road Access', 'Gated Community Security'],
    description: "Premium plot for custom building. Gated entrance, wide asphalt roads, complete municipal water lines connected directly.",
    yearBuilt: 2023,
    furnishing: 'Unfurnished',
    facing: 'East Facing',
    developer: 'Amanora Group',
    rera: 'P52100041241',
    coordinates: { lat: 18.5140, lng: 73.9422 },
    listingType: 'Resale',
    propertyType: 'Land/Plot',
    bhkType: 'Plot',
    locality: 'Hadapsar',
    plotArea: '2000-5000',
  },
  {
    title: 'Model Colony Sovereign Duplex',
    type: 'Apartment',
    category: 'Luxury Apartments',
    price: 52000000,
    priceLabel: '₹5.2 Cr',
    location: 'Model Colony, Pune',
    city: 'Pune',
    bedrooms: 4,
    bathrooms: 4,
    area: 3400,
    parking: 2,
    image: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800&q=80',
    images: ['https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800&q=80'],
    badge: 'Popular',
    badgeColor: 'gold',
    status: 'Ready to Move',
    featured: true,
    amenities: ['Private Elevator', '24x7 Security Grid', 'Rooftop Lawn', 'EV Car Charger'],
    description: "Luxurious 4 BHK duplex penthouse apartment located in Model Colony. Double height lounge deck, Vastu compliant design facing east.",
    yearBuilt: 2024,
    furnishing: 'Fully Furnished',
    facing: 'East Facing',
    developer: 'VTP Realty',
    rera: 'P52100041242',
    coordinates: { lat: 18.5305, lng: 73.8378 },
    listingType: 'Resale',
    propertyType: 'Residential',
    bhkType: '4 BHK',
    locality: 'Model Colony',
    propertyAge: 'Ready to Move',
  },
  {
    title: 'Camp Colonial Heritage Bungalow',
    type: 'Villa',
    category: 'Luxury Villas',
    price: 195000000,
    priceLabel: '₹19.5 Cr',
    location: 'Camp, Pune',
    city: 'Pune',
    bedrooms: 6,
    bathrooms: 6,
    area: 9200,
    parking: 5,
    image: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&q=80',
    images: ['https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&q=80'],
    badge: 'Historic Estate',
    badgeColor: 'gold',
    status: 'Ready to Move',
    featured: true,
    amenities: ['Surrounding Forest Garden', 'Infinity Swimming Pool', 'Vintage Fireplace', 'Outhouse Quarters'],
    description: "An authentic historic colonial style residential bungalow estate in Camp. Restored to perfection with Italian marble flooring, modern kitchen, and security.",
    yearBuilt: 2023,
    furnishing: 'Fully Furnished',
    facing: 'North-East Facing',
    developer: 'Goel Ganga Developments',
    rera: 'P52100041243',
    coordinates: { lat: 18.5204, lng: 73.8820 },
    listingType: 'Resale',
    propertyType: 'Villa',
    bhkType: '5 BHK', // For BHK filter matches
    locality: 'Camp',
    propertyAge: '10+ years',
  },
  {
    title: 'Wakad Smart Living Suite',
    type: 'Apartment',
    category: 'Premium Apartments',
    price: 9500000,
    priceLabel: '₹95 Lakhs',
    location: 'Wakad, Pune',
    city: 'Pune',
    bedrooms: 2,
    bathrooms: 2,
    area: 1050,
    parking: 1,
    image: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&q=80',
    images: ['https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&q=80'],
    badge: 'Ready to Move',
    badgeColor: 'green',
    status: 'Ready to Move',
    featured: false,
    amenities: ['24x7 Water Supply', 'Children Play Arena', 'Solar Water Heaters', 'CCTV Security Grid'],
    description: "Charming, centrally connected luxury apartment in Wakad. East-facing unit with large bay window frames overlooking the podium landscape parks.",
    yearBuilt: 2023,
    furnishing: 'Semi Furnished',
    facing: 'East Facing',
    developer: 'VTP Realty',
    rera: 'P52100041244',
    coordinates: { lat: 18.5980, lng: 73.7533 },
    listingType: 'Resale',
    propertyType: 'Residential',
    bhkType: '2 BHK',
    locality: 'Wakad',
    propertyAge: '1-3 years',
  },
  {
    title: 'Ganga Dham Vastu Apartment',
    type: 'Apartment',
    category: 'Premium Apartments',
    price: 32000000,
    priceLabel: '₹3.2 Cr',
    location: 'Ganga Dham, Pune',
    city: 'Pune',
    bedrooms: 3,
    bathrooms: 3,
    area: 2100,
    parking: 2,
    image: 'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=800&q=80',
    images: ['https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=800&q=80'],
    badge: 'Hot Deal',
    badgeColor: 'red',
    status: 'Ready to Move',
    featured: true,
    amenities: ['Vastu Compliant', 'Banquet Hall', 'Indoor Games Arena', 'CCTV Security Grid'],
    description: "Elegant, centrally connected luxury apartment in Ganga Dham. Completely Vastu compliant facing east, featuring premium Italian modular kitchen units.",
    yearBuilt: 2024,
    furnishing: 'Fully Furnished',
    facing: 'East Facing',
    developer: 'Goel Ganga Developments',
    rera: 'P52100041247',
    coordinates: { lat: 18.4789, lng: 73.8655 },
    listingType: 'Resale',
    propertyType: 'Residential',
    bhkType: '3 BHK',
    locality: 'Ganga Dham',
    propertyAge: 'Ready to Move',
  },
  {
    title: 'Katraj Lakeview Villa',
    type: 'Villa',
    category: 'Luxury Villas',
    price: 52000000,
    priceLabel: '₹5.2 Cr',
    location: 'Katraj, Pune',
    city: 'Pune',
    bedrooms: 4,
    bathrooms: 4,
    area: 3900,
    parking: 3,
    image: 'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800&q=80',
    images: ['https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800&q=80'],
    badge: 'Exclusive',
    badgeColor: 'gold',
    status: 'Ready to Move',
    featured: false,
    amenities: ['Lake View Deck', 'Lush Landscaping', 'Solar Heaters', 'Staff Quarters'],
    description: "Private contemporary villa facing the serene waters of Katraj Lake. Fully customized with marble finishes, large walk-in wardrobes, and solar power setup.",
    yearBuilt: 2023,
    furnishing: 'Semi Furnished',
    facing: 'North Facing',
    developer: 'Amit Enterprises',
    rera: 'P52100041248',
    coordinates: { lat: 18.4525, lng: 73.8545 },
    listingType: 'Resale',
    propertyType: 'Villa',
    bhkType: '4 BHK',
    locality: 'Katraj',
    propertyAge: '1-3 years',
  },
];

async function seed() {
  try {
    await mongoose.connect(process.env.MONGO_URI);
    console.log('✅ MongoDB connected');

    // Fetch seeded agents
    const agents = await User.find({ role: 'agent' });
    console.log(`👤 Found ${agents.length} agents in the database`);

    // Dynamically assign properties based on location match
    for (const p of properties) {
      const locName = p.location.split(',')[0].trim().toLowerCase();
      
      const matchingAgent = agents.find(a => {
        if (!a.expertise) return false;
        const areas = a.expertise.split(',').map(s => s.trim().toLowerCase());
        return areas.some(area => area === locName || locName.includes(area) || area.includes(locName));
      });

      if (matchingAgent) {
        p.agent = {
          id: matchingAgent._id,
          name: matchingAgent.name,
          phone: matchingAgent.phone
        };
      } else {
        // Fallback: assign to a random agent
        const randomAgent = agents[Math.floor(Math.random() * agents.length)];
        if (randomAgent) {
          p.agent = {
            id: randomAgent._id,
            name: randomAgent.name,
            phone: randomAgent.phone
          };
        }
      }
    }

    // Clean up existing properties
    await Property.deleteMany({});
    console.log('🧹 Cleared existing properties database');

    const inserted = await Property.insertMany(properties);
    console.log(`🏠 Seeded ${inserted.length} Pune properties successfully with matched agent assignments!`);
  } catch (err) {
    console.error('❌ Seed failed:', err.message);
  } finally {
    await mongoose.disconnect();
    console.log('🔌 MongoDB disconnected');
  }
}

seed();
